### ISSUE TITLE
Could not copy forceFullDesktopBar

### ISSUE THREAD

**Issue by matthewbshaw** [briankendall/forceFullDesktopBar#1]
Followed instructions, can't seem to get beyond the following terminal issue (see below). The helper text tells me to use the directory containing bootstrap.dylib, dockInjection.dylib, etc which don't exist anywhere.

sudo ./install.sh
forceFullDesktopBar is a directory (not copied).
Could not copy forceFullDesktopBar. Make sure you're running this script for the directory that contains: forceFullDesktopBar, bootstrap.dylib, dockInjection.dylib, net.briankendall.forceFullDesktopBar.plist

**Comment by briankendall** [comment]
Whoops, that text should read "Make sure you're running this script *in* the directory that contains: forceFullDesktopBar, bootstrap.dylib, dockInjection.dylib, net.briankendall.forceFullDesktopBar.plist"

Basically, if you run the script in the forceFullDesktopBar directory that results from extracting the zip file in the release section, it should work.

**Comment by evan-masseau** [comment]
I had the same issue as the first commenter at first... turned out it was because I cloned your git repo instead of downloading the release .zip package. In case of other dummies like me you may want to specify the difference in your readme.
Anyway it worked for me, so thanks a bunch!

**Comment by MasterSmollett** [comment]
I'm running the sript from the right folder and getting an error:

forceFullDesktopBar-master toby$ sudo ./install.sh
cp: forceFullDesktopBar is a directory (not copied).
Could not copy forceFullDesktopBar. Make sure you're running this script for the directory that contains: forceFullDesktopBar, bootstrap.dylib, dockInjection.dylib, net.briankendall.forceFullDesktopBar.plist 

Any ideas? I'd really love to get this working.

**Comment by evan-masseau** [comment]
When i was getting that error it turned out to be because i cloned the repo instead of downloading the release. Did you download the zip from here?
https://github.com/briankendall/forceFullDesktopBar/releases

**Comment by briankendall** [comment]
I just updated the repo so that people who cloned it can install. There is now an install directory containing the installation script and all the necessary files. Hopefully this will prevent any further confusion!
