### ISSUE TITLE
Any chance we'll see a Big Sur compatible version?

### ISSUE THREAD

**Issue by Arcrammer** [briankendall/forceFullDesktopBar#10]
Really missing this from Catalina! Since updating to Big Sur (10.16) I have not had any luck with reinstalling.

**Comment by briankendall** [comment]
I haven't had a chance to test on Big Sur yet, but there was a security update to macOS 10.14.6 that caused mach_inject to crash, which forceFullDesktopBar uses to modify the Dock. The same change might also affect Big Sur. If that's the case then I'm not going to be able to update forceFullDesktopBar until there's a fix to mach_inject.

In the meantime you might be able to use [missionControlFullDesktopBar](https://github.com/briankendall/missionControlFullDesktopBar) as an alternative. I haven't tested it in Big Sur yet, but that doesn't require disabling SIP or injecting anything into the Dock so it may work better.

**Comment by Arcrammer** [comment]
I'll give it a try and see how my luck goes. Thanks!!

**Comment by saagarjha** [comment]
FWIW, it worked fine for me after I cleaned up the version check. YMMV :)

**Comment by briankendall** [comment]
@saagarjha Thanks for looking into that! I'll make a fix sometime in the coming days.
