### ISSUE TITLE
Compatible with Big Sur?

### ISSUE THREAD

**Issue by jasonhan-vassar** [briankendall/forceFullDesktopBar#13]
Hi, I've been using your tweak for pretty much as long as I've had my Mac! It's been a change that should be in stock macOS in my opinion. Unfortunately, it stopped working after upgrading to macOS 11.0.1, can you or anyone else reproduce this? I have tried reinstalling to no success. I am on the MacBook Pro 2019 if that changes things.

**Comment by briankendall** [comment]
I just made a new build that should work in Big Sur: https://github.com/briankendall/forceFullDesktopBar/releases/tag/v1.1.2

**Comment by jasonhan-vassar** [comment]
Thanks so much for the quick response! I can confirm it works nicely again :)
