### ISSUE TITLE
Kernel panics in macOS Ventura beta on Apple Silicon

### ISSUE THREAD

**Issue by briankendall** [briankendall/forceFullDesktopBar#17]
Running forceFullDesktopBar results in kernel panics in macOS Ventura beta 8 + Apple Silicon

**Comment by roelvangils** [comment]
@briankendall what is the current status on this? Is it safe yet? 🙂 I'm currently using this [BetterTouchTool](https://folivora.ai/) action to do the same thing, but it's a bit wonky and it uses AppleScript to quickly move the mouse cursor to the top and back.

![20230503_211254_BetterTouchTool@2x](https://user-images.githubusercontent.com/103744/236020533-10f6e225-7dfd-42b3-b285-4136b9eaa707.png)

**Comment by briankendall** [comment]
I've been sitting on this for too long! Looks like updating forceFullDesktopBar to use the latest version of Frita fixes any Ventura issues, if the updates to Ventura didn't fix them too.

@roelvangils Give this release a try and let me know if it works: https://github.com/briankendall/forceFullDesktopBar/releases/tag/v1.2.1

**Comment by roelvangils** [comment]
This works like a charm! 😁 I do wonder: what if Apple issues an OS Update? Should I be worried about kernel panics then?

**Comment by briankendall** [comment]
@roelvangils Glad to hear it works! I'll consider this issue closed.

And yes, always be concerned about compatibility and kernel panics. Ventura is the first time the method forceFullDesktopBar uses to inject code into the Dock caused a kernel panic, and it was _probably_ due to Ventura still being in beta at the time. But I can't predict what sorts of effects a new release of macOS will have. Usually incompatibilities either make it so that forceFullDesktopBar silently fails, or it causes the Dock to crash. Kernel panics are rare with macOS. (Or at least they used to be... 😒)

Generally though, a minor update should maintain compatibility, e.g. something like macOS 13.2 to 13.3 should be fine. A major update though may break forceFullDesktopBar, which was the case for macOS 12 to 13. If you upgrade, I'd recommend waiting until I or someone else tests it out and reports back. Unless you want to be a guinea pig and take the risk, in which case, by all means try it out and let me know how it works.

**Comment by TJennerjahn** [comment]
The README still says that the current version causes kernel panics. Is that just outdated, or is there another reason why this shouldn't be installed on ventura + apple silicon macs?

**Comment by briankendall** [comment]
@TJennerjahn No, I had just forgotten to remove that warning.
