### ISSUE TITLE
csrutil command gives me "command not found"

### ISSUE THREAD

**Issue by spacewaffle** [briankendall/forceFullDesktopBar#3]
Restarting in recovery mode with Cmd + option + r gave me net recovery mode, where csrutil doesn't work. I tried rebooting using Cmd + r, which worked. Using El Capitan.

**Comment by mpodshivalin** [comment]
That is correct, I had similar issue. Cmd+R worked.

**Comment by ahnbizcad** [comment]
for me, it gave me this error

`csrutil enable --without debug
csrutil: requesting an unsupported configuration. This is likely to break in the future and leave your machine in an unknown state.
csrutil: failed to modify system integrity configuration. This tool needs to be executed from the Recovery OS.`
