### ISSUE TITLE
Magic Mouse 2

### ISSUE THREAD

**Issue by tylerlovesapples** [briankendall/forceFullDesktopBar#8]
When using the Magic Mouse 2's (the one with the built-in battery) two-finger double-tap feature to activate mission control, MacOS's default behavior of hiding desktops happens.

**Comment by briankendall** [comment]
Sorry for not responding to this sooner. Unfortunately I don't have a Magic Mouse 2 at the moment so I'm currently unable to reproduce and fix the issue. I'll see if I can get my hands on one for testing at some point though. I'd certainly like this utility to consistently change Mission Control's behavior.

**Comment by briankendall** [comment]
@tylerlovesapples I got my hands on a Magic Mouse 2 and I believe I've got forceFullDesktopBar working with them now. Can you try out [version 1.1.1](https://github.com/briankendall/forceFullDesktopBar/releases/tag/v1.1.1) and let me know if it works for you too?
